"""add field invalidate_before for user table

Revision ID: 0ad3cfb2d80f
Revises: 279cf2ea0135
Create Date: 2025-04-17 15:02:34.915247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad3cfb2d80f'
down_revision: Union[str, None] = '279cf2ea0135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invalidate_before', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invalidate_before')
    # ### end Alembic commands ###
